name: update-cl2

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"   # اجرای cl2.py هر ۸ ساعت

permissions:
  contents: write

jobs:
  cl2-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # مرحله 1: دریافت سورس
      - uses: actions/checkout@v4

      # مرحله 2: نصب Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # مرحله 3: نصب وابستگی‌ها
      - run: pip install requests psutil retrying PyYaml || echo "skip install"

      # مرحله 4: اجرای اسکریپت cl4.py با timeout
      - run: timeout 600s python cl2.py || echo "❌ cl2.py failed or skipped"

      # مرحله 5: commit و push فایل‌های خروجی اختصاصی cl4
      - run: |
          if [[ -s normal2.json || -s final2.json ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add normal2.json final2.json
            git commit -m "auto update from cl2.py [skip ci]" || echo "No changes"
            git push || echo "skip push"
          else
            echo "⚠️ normal2.json یا final2.json خالی یا موجود نیست، commit نشد"
          fi
